version: "3"
services:
  backend:
    container_name: "studentbook-next-crud-backend"
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/backend
    networks:
      - studentbook-next-crud-network
    restart: always
  frontend:
    container_name: "studentbook-next-crud-frontend"
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env_file:
      - ./frontend/.env
    ports:
      - "80:3000"
      - "443:3000"
    volumes:
      - ./frontend:/frontend
    networks:
      - studentbook-next-crud-network
    restart: always
networks:
  studentbook-next-crud-network:
    name: studentbook-next-crud-network
